### ISSUE TITLE
Feat (planning): Design a consistent API for third-party REST API client wrappers

### ISSUE THREAD

**Issue by neoncitylights** [elliniaresearch/app#5]
```[tasklist]
### Tasks
- [ ] https://github.com/wandering-app/app/issues/10
- [ ] https://github.com/wandering-app/app/issues/11
- [ ] https://github.com/wandering-app/app/issues/12
```
